# screen
SCREEN_WIDTH, SCREEN_HEIGHT = 1200, 800

# map
BLOCK_SIZE = 40
MAP_WIDTH, MAP_HEIGHT = SCREEN_WIDTH // BLOCK_SIZE, SCREEN_HEIGHT // BLOCK_SIZE

# role
PLAYER_HEALTH = 100
INIT_POS_X = SCREEN_WIDTH // 2 - BLOCK_SIZE
INIT_POS_Y = SCREEN_HEIGHT - 2 * BLOCK_SIZE


# fight panel
FIGHT_PANEL_WIDTH = 600
FIGHT_PANEL_HEIGHT = 400
FIGHT_PANEL_POS_X = 300
FIGHT_PANEL_POS_Y = 200


# merchant
OVERAGE = 100
